version: '3.8'
services:

  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  mssql:
    image: chriseaton/adventureworks:latest
    container_name: lde.mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 1My_password
    ports:
      - 1434:1433

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: lde.cloudbeaver
    ports:
      - 8002:8978

  examproject.api:
    build:
      context: .
      dockerfile: ExamProject.API/Dockerfile  
    container_name: lde.examproject.api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:5000
     - ConnectionString=server=www.alevelwebsite.com;port=5433;database=MyShop;uid=postgres;password=postgres;
    ports:
      - 5000:5000
    depends_on:
      - postgres

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.4